[build]
  command = "nx build ngx-wysicat --configuration production && nx build demo --configuration production"
  publish = "dist/demo/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
